sudo: false
dist: trusty
language: rust
rust:
- nightly

before_script:
  - |
      git clone --depth 1 -b stable https://github.com/jedisct1/libsodium.git
      cd libsodium
      ./autogen.sh
      ./configure --prefix=$HOME
      make
      make install
      cd ..
      wget https://github.com/zeromq/zeromq4-1/archive/v4.1.6.tar.gz
      tar zxf v4.1.6.tar.gz
      cd zeromq4-1-4.1.6
      ./autogen.sh
      ./configure --prefix=$HOME --with-libsodium
      make
      make install
      cd ..

env:
  global:
    # for zmq
    - PATH=$HOME/.local/bin:$PATH
    - LD_LIBRARY_PATH=$HOME/lib
    - PKG_CONFIG_PATH=$HOME/lib/pkgconfig
    # override the default `--features unstable` used for the nightly branch
    - TRAVIS_CARGO_NIGHTLY_FEATURE=""
