[package]
name = "pericortex"
version = "0.1.0"
authors = ["Deyan Ginev <d.ginev@jacobs-university.de>"]

[lib]
name = "pericortex"
crate-type = ["rlib", "dylib", "staticlib"]

[dependencies.libarchive-sys]
git = "https://github.com/dginev/libarchive-sys.git"

[dependencies.zmq]
git = "https://github.com/erickt/rust-zmq.git"

[dependencies]
libc = "0.2.17"
regex = "0.1.80"
rustc-serialize = "0.3"
rand = "0.3.14"
tempfile = "2.1.4"